databases:
  - name: postgres
    databaseName: notion_app
    user: notion_app_user
services:
  - type: web
    name: guesty
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Notion_App
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false