default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("PG_USERNAME") { 'postgres' } %>
  password: <%= ENV.fetch("PG_PASSWORD") { 'postgres' } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: notion_app_development

test:
  <<: *default
  database: notion_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  
queue:
  <<: *default
  database: queue

cache:
  <<: *default
  database: cache